apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  generation: 1
  name: gw1
  namespace: demo
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - demoapp-envoy.ea.demo.dckr.org
    port:
      name: http80
      number: 80
      protocol: HTTP
